devfs: remove unused variable in devfs_lookup()
Fedora 44 ships GCC 16, which extends -Wunused-but-set-variable: it now
also warns about a variable whose only uses are increments, such as the
counter "i" in devfs_lookup(), which was incremented but never read.
Because OSv builds with -Werror, this warning broke the build:

  fs/devfs/devfs_vnops.cc:131:20: error: variable 'i' set but not used
      [-Werror=unused-but-set-variable=]

Remove the unused variable.