Fix compilation error in uips_socket.cc
Error message:

bsd/sys/kern/uipc_socket.cc: In function 'socket* soalloc(vnet*)':
bsd/sys/kern/uipc_socket.cc:245:58: error: expected ')' before 'PRIx64'
  uipc_d("soalloc() so=%" PRIx64, (uint64_t)so);
                                                          ^

This was introduced in one of these commits:
c506516b14d32e416f4a9247869a1a89f7e9c413
406a93ed446506bd912e2c5e94255bf8792d868d

As suggested by Pekka including <cinttypes> is the proper fix for C++11.

Signed-off-by: Tomasz Grabiec <tgrabiec@cloudius-systems.com>
Signed-off-by: Pekka Enberg <penberg@cloudius-systems.com>