musl: stop older gcc produce warnings caused by usage of strncpy
When bulding OSv on Travis which uses gcc 7.5.0 we get an compilation warning like so:

musl/src/network/if_nametoindex.c:14:2: error: 'strncpy' specified bound 16 equals destination size [-Werror=stringop-truncation]
   14 |  strncpy(ifr.ifr_name, name, sizeof ifr.ifr_name);

There is a similar one caused by the usage of strncpy in if_indextoname.c.

At some point I sent an email to musl about changing strncpy to strlcpy
and you can see Rich Felker's response here:
https://inbox.vuxu.org/musl/20200817235454.GC3265@brightrain.aerifal.cx/T/#t

There is also an interesting article about strlcpy() here - https://lwn.net/Articles/507319/.

It is also interesting that newer gcc (> 11.0.0 but possible older as well) does not raise
this warning about strncpy which might mean it is sometimes treated as false positive (see this gcc
issue https://gcc.gnu.org/legacy-ml/gcc-patches/2018-08/msg01549.html).

One way to fix this problem would be to change strncpy to strlcpy in those
two musl source files which would mean to bring those as copies. I chose
to turn off this warning for these 2 sources instead.

Signed-off-by: Waldemar Kozaczuk <jwkozaczuk@gmail.com>