Revert "conf: make release build use -O3"
This reverts commit 4af010f18bd9656cf021303ab2c4f86a155e3212.

This change causes OSv to abort when JVM is started with
the following options:

 -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005

Result:

ERROR: transport error 202: setsockopt TCPNODELAY failed: Protocol not available
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [../../../src/share/back/debugInit.c:750]
FATAL ERROR in native method: JDWP No transports initialized, jvmtiError=AGENT_ERROR_TRANSPORT_INIT(197)
Aborted

I think it's best to revert it until the root cause is solved.

See issue #167

Signed-off-by: Tomasz Grabiec <tgrabiec@cloudius-systems.com>
Signed-off-by: Pekka Enberg <penberg@cloudius-systems.com>