setup.py: fix regression on Ubuntu 14.04/Fedora 20
This patch fixes a "no attribute" error:

Traceback (most recent call last):
  File "./scripts/setup.py", line 98, in <module>
    if dver.ec2_post_install:
AttributeError: type object 'Ubuntu_14_04' has no attribute 'ec2_post_install'

Signed-off-by: Dmitry Fleytman <dmitry@daynix.com>
Signed-off-by: Pekka Enberg <penberg@cloudius-systems.com>