fix compatibility features.h for Fedora 34
Recently (for example in Fedora 34), the C++ header files started to
include the system's <single_threaded.h>, and that include <features.h>
and assumes it is enough to define __BEGIN_DECLS. However, this macro
is actually defined in <sys/cdefs.h>, so we get many build errors like:

/usr/include/sys/single_threaded.h:24:1: error: ‘__BEGIN_DECLS’ does not name a type
   24 | __BEGIN_DECLS
      | ^~~~~~~~~~~~~

The fix is to include <sys/cdefs.h> from our compatibility <features.h>.
This is what glibc does too.

Signed-off-by: Nadav Har'El <nyh@scylladb.com>
Message-Id: <20210614062057.1998552-2-nyh@scylladb.com>