Http Server: Fix include path in Makefile
Fixes build breakage caused by commit c69fad2 ("Http Server: Clean up
<api/os.hh>"):

  CXX obj/api/os.o
In file included from api/os.cc:9:0:
api/os.hh:14:21: fatal error: routes.hh: No such file or directory
 #include "routes.hh"
                     ^

Signed-off-by: Pekka Enberg <penberg@cloudius-systems.com>