Fix build with GNU Make < 3.82
The 'define' form with '=' was introduced in GNU Make 3.82
and has the same meaning as without.

The default 'make' in Ubuntu 13.04 is stil on 3.81. Let's
drop '=' for better compatibility.

Symptoms:
 make[1]: Entering directory `~/src/osv/build/release'
      CC bsd/cddl/contrib/opensolaris/cmd/zpool/zpool_iter.o
    ../../bsd/cddl/contrib/opensolaris/cmd/zpool/zpool_iter.c:28:21:\
 fatal error: solaris.h: No such file or     directory
     #include <solaris.h>
                         ^
    compilation terminated.

Signed-off-by: Tomasz Grabiec <tgrabiec@cloudius-systems.com>