gdb: fix error on connect
When "connect"ing to OSv with gdb, I always get the following message:

   Traceback (most recent call last):
   File "/home/nyh/osv/scripts/loader.py", line 137, in invoke
   status_enum.running = gdb.parse_and_eval('sched::thread::running')
   gdb.error: There is no field named running

We need to change from 'sched::thread::running' to include the name of
the enum: 'sched::thread::status::running'.

I don't know why this worked before without this error. Maybe gdb
changed its behavior recently?

Signed-off-by: Nadav Har'El <nyh@cloudius-systems.com>
Signed-off-by: Avi Kivity <avi@cloudius-systems.com>