musl: don't use _GNU_SOURCE
Some of the musl files, like math/exp10.c, do
  #define _GNU_SOURCE

So for the musl files, we shouldn't define this _GNU_SOURCE on our own,
otherwise we get a compilation error:

/home/nyh/osv/musl/src/math/exp10.c:1:0: error: "_GNU_SOURCE" redefined [-Werror]

Note we always had this override for libc/, now that we are moving the
source files, we need to do this for musl/ as well.

Signed-off-by: Nadav Har'El <nyh@cloudius-systems.com>
Signed-off-by: Avi Kivity <avi@cloudius-systems.com>