mman: Fix missing libc.hh include
Fixes the following build brekage caused by commit a7d6b26 ("mman: Use
libc_error() in mprotect()"):

../../libc/mman.cc: In function ‘int mprotect(void*, size_t, int)’:
../../libc/mman.cc:36:33: error: ‘libc_error’ was not declared in this scope
         return libc_error(EINVAL);
                                 ^
../../libc/mman.cc:41:33: error: ‘libc_error’ was not declared in this scope
         return libc_error(ENOMEM);
                                 ^
  CXX libc/pipe_buffer.o
  CXX libc/pipe.o
make[1]: *** [libc/mman.o] Error 1