bsd: Fix printf format string
Spotted by GCC with '-Wformat=1':

../../bsd/sys/netinet/tcp_subr.c: In function ‘tcp_log_addr’:
../../bsd/sys/netinet/tcp_subr.c:2286:3: warning: unknown conversion type character ‘b’ in format [-Wformat=]
   sprintf(sp, " tcpflags 0x%b", th->th_flags, PRINT_TH_FLAGS);
   ^
../../bsd/sys/netinet/tcp_subr.c:2286:3: warning: too many arguments for format [-Wformat-extra-args]

BSD has some nice printf extension for printing out bitfields. We don't
so switch to hexadecimal output.

Signed-off-by: Pekka Enberg <penberg@cloudius-systems.com>